# Generated by Django 2.0.2 on 2018-03-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setchoices',
            name='id',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='id',
        ),
        migrations.AlterField(
            model_name='setchoices',
            name='place_name',
            field=models.CharField(max_length=250, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='roll_num',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
