# Generated by Django 2.0.2 on 2018-03-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0002_auto_20180315_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date', models.DateField(max_length=40)),
            ],
        ),
    ]
